In [1]:
import torch

### First Tensor
Creating tensors with different dimentions using pytorch

In [2]:
tensor = torch.tensor(5) # scalar

# 1 dimentional tensor
tensor1 = torch.tensor([3,2,5,6,3,6,3])  # vector 
print(tensor1.shape)

# 2 dimentional tensor
# matrix
tensor2 = torch.tensor([[1,2,3,4,5],
                        [6,7,8,9,0]])

# [4,5] tensor with random elements; rand(dim) method creates ramdom tensor with given dimention 
random_tensor = torch.rand([4,5])
random_tensor

torch.Size([7])


tensor([[0.2550, 0.7594, 0.1825, 0.7959, 0.2660],
        [0.5526, 0.8081, 0.1464, 0.1234, 0.0209],
        [0.3384, 0.1631, 0.0543, 0.4963, 0.4736],
        [0.3217, 0.9366, 0.9855, 0.5443, 0.0307]])

In [16]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [3]:
# shape of the tensor
tensor1.shape
# OR
tensor1.size()

torch.Size([7])

### Tensor Datatypes

Tensors can have many datatype such as float16, float32, int32, int16 etc.
tensor.dtype contain data type of the tensor

In [4]:
# tensor.dtype contain data type of the tensor
random_tensor.dtype

torch.float32

In [7]:
# changing type of a tensor: type()
f16tensor = random_tensor.type(torch.float16)
f16tensor.dtype

torch.float16

### Tensor aggregation
finding min, max, sum, mean etc of a tensor

In [10]:
x = torch.tensor([1,2,3,4,5,6,7,8])

# finding min and max of the tensor x
torch.min(x), torch.max(x)
# OR
x.min(),x.max()

(tensor(1), tensor(8))

In [12]:
#finding sum of the tensor
torch.sum(x), x.sum()

(tensor(36), tensor(36))

In [13]:
# finding the mean of the tensor x
# to find the mean, the tensor have to be floating point or complex dtype
# x.mean() or torch.mean(x) don't work, because dtype of tensor x in int64 (long)
x = x.type(torch.float32)
x.mean(), torch.mean(x)

(tensor(4.5000), tensor(4.5000))

In [18]:
# finding positional min and max (position of the min and max elment in the tensor)

x.argmin(), x.argmax()

(tensor(0), tensor(7))

### Manipulating tensors (Tensor operations)

Tensor operations:
* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matix Multiplication

In [28]:
tensor = torch.rand([4,4])
tensor

tensor([[0.2607, 0.8618, 0.9763, 0.7213],
        [0.6898, 0.3211, 0.4672, 0.0916],
        [0.7359, 0.4593, 0.9698, 0.6946],
        [0.2346, 0.3074, 0.5314, 0.4972]])

In [37]:
# Addition
tensor + 1, torch.add(tensor,1), tensor.add(1)

(tensor([[1.2607, 1.8618, 1.9763, 1.7213],
         [1.6898, 1.3211, 1.4672, 1.0916],
         [1.7359, 1.4593, 1.9698, 1.6946],
         [1.2346, 1.3074, 1.5314, 1.4972]]),
 tensor([[1.2607, 1.8618, 1.9763, 1.7213],
         [1.6898, 1.3211, 1.4672, 1.0916],
         [1.7359, 1.4593, 1.9698, 1.6946],
         [1.2346, 1.3074, 1.5314, 1.4972]]),
 tensor([[1.2607, 1.8618, 1.9763, 1.7213],
         [1.6898, 1.3211, 1.4672, 1.0916],
         [1.7359, 1.4593, 1.9698, 1.6946],
         [1.2346, 1.3074, 1.5314, 1.4972]]))

In [38]:
#subtaction
tensor - 1, torch.subtract(tensor,1), tensor.subtract(1)

(tensor([[-0.7393, -0.1382, -0.0237, -0.2787],
         [-0.3102, -0.6789, -0.5328, -0.9084],
         [-0.2641, -0.5407, -0.0302, -0.3054],
         [-0.7654, -0.6926, -0.4686, -0.5028]]),
 tensor([[-0.7393, -0.1382, -0.0237, -0.2787],
         [-0.3102, -0.6789, -0.5328, -0.9084],
         [-0.2641, -0.5407, -0.0302, -0.3054],
         [-0.7654, -0.6926, -0.4686, -0.5028]]),
 tensor([[-0.7393, -0.1382, -0.0237, -0.2787],
         [-0.3102, -0.6789, -0.5328, -0.9084],
         [-0.2641, -0.5407, -0.0302, -0.3054],
         [-0.7654, -0.6926, -0.4686, -0.5028]]))

In [31]:
# Element wise multiplication
tensor * 3, torch.mul(tensor,3), tensor.mul

tensor([[0.7820, 2.5854, 2.9289, 2.1640],
        [2.0693, 0.9634, 1.4016, 0.2749],
        [2.2078, 1.3780, 2.9093, 2.0839],
        [0.7037, 0.9221, 1.5942, 1.4915]])

In [32]:
# Division
tensor / 2

tensor([[0.1303, 0.4309, 0.4881, 0.3607],
        [0.3449, 0.1606, 0.2336, 0.0458],
        [0.3680, 0.2297, 0.4849, 0.3473],
        [0.1173, 0.1537, 0.2657, 0.2486]])

### Matrix multiplication (Multiplying Tensors)
Rules of matric multiplication
* The inner dimention of two tensors must be same
    - `(3,2) * (3,4)` won't work
    - `(3,2) * (2,4)` will work
* The dimention of the result will be same as the outer dimentions of the operant matrices
    - `(3,2) * (4,2)` will result the matrix with the shape of `(2,4)`

In [36]:
# note that the inner dimentions of Tensors "tensor" and "tensor2"
tensor2 = torch.rand([4,6])
tensor.shape

torch.Size([4, 4])