In [1]:
import torch

### First Tensor
Creating tensors with different dimentions using pytorch

In [2]:
tensor = torch.tensor(5) # scalar

# 1 dimentional tensor
tensor1 = torch.tensor([3,2,5,6,3,6,3])  # vector 
print(tensor1.shape)

# 2 dimentional tensor
# matrix
tensor2 = torch.tensor([[1,2,3,4,5],
                        [6,7,8,9,0]])

# [4,5] tensor with random elements; rand(dim) method creates ramdom tensor with given dimention 
random_tensor = torch.rand([4,5])
random_tensor

torch.Size([7])


tensor([[0.1149, 0.2406, 0.7541, 0.1170, 0.0234],
        [0.1163, 0.7969, 0.4463, 0.1939, 0.2865],
        [0.9927, 0.2708, 0.7071, 0.1585, 0.5880],
        [0.2506, 0.9943, 0.1326, 0.1051, 0.3902]])

In [3]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [4]:
# shape of the tensor
tensor1.shape
# OR
tensor1.size()

torch.Size([7])

### Tensor Datatypes

Tensors can have many datatype such as float16, float32, int32, int16 etc.
tensor.dtype contain data type of the tensor

In [5]:
# tensor.dtype contain data type of the tensor
random_tensor.dtype

torch.float32

In [6]:
# changing type of a tensor: type()
f16tensor = random_tensor.type(torch.float16)
f16tensor.dtype

torch.float16

### Tensor aggregation
finding min, max, sum, mean etc of a tensor

In [7]:
x = torch.tensor([1,2,3,4,5,6,7,8])

# finding min and max of the tensor x
torch.min(x), torch.max(x)
# OR
x.min(),x.max()

(tensor(1), tensor(8))

In [8]:
#finding sum of the tensor
torch.sum(x), x.sum()

(tensor(36), tensor(36))

In [9]:
# finding the mean of the tensor x
# to find the mean, the tensor have to be floating point or complex dtype
# x.mean() or torch.mean(x) don't work, because dtype of tensor x in int64 (long)
x = x.type(torch.float32)
x.mean(), torch.mean(x)

(tensor(4.5000), tensor(4.5000))

In [10]:
# finding positional min and max (position of the min and max elment in the tensor)

x.argmin(), x.argmax()

(tensor(0), tensor(7))

### Manipulating tensors (Tensor operations)

Tensor operations:
* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matix Multiplication

In [11]:
tensor = torch.rand([4,4])
tensor

tensor([[0.7177, 0.6364, 0.6668, 0.7803],
        [0.9246, 0.9254, 0.4535, 0.5621],
        [0.3097, 0.2076, 0.4416, 0.8025],
        [0.1477, 0.1693, 0.7068, 0.4113]])

In [12]:
# Addition
tensor + 1, torch.add(tensor,1), tensor.add(1)

(tensor([[1.7177, 1.6364, 1.6668, 1.7803],
         [1.9246, 1.9254, 1.4535, 1.5621],
         [1.3097, 1.2076, 1.4416, 1.8025],
         [1.1477, 1.1693, 1.7068, 1.4113]]),
 tensor([[1.7177, 1.6364, 1.6668, 1.7803],
         [1.9246, 1.9254, 1.4535, 1.5621],
         [1.3097, 1.2076, 1.4416, 1.8025],
         [1.1477, 1.1693, 1.7068, 1.4113]]),
 tensor([[1.7177, 1.6364, 1.6668, 1.7803],
         [1.9246, 1.9254, 1.4535, 1.5621],
         [1.3097, 1.2076, 1.4416, 1.8025],
         [1.1477, 1.1693, 1.7068, 1.4113]]))

In [13]:
#subtaction
tensor - 1, torch.subtract(tensor,1), tensor.subtract(1)

(tensor([[-0.2823, -0.3636, -0.3332, -0.2197],
         [-0.0754, -0.0746, -0.5465, -0.4379],
         [-0.6903, -0.7924, -0.5584, -0.1975],
         [-0.8523, -0.8307, -0.2932, -0.5887]]),
 tensor([[-0.2823, -0.3636, -0.3332, -0.2197],
         [-0.0754, -0.0746, -0.5465, -0.4379],
         [-0.6903, -0.7924, -0.5584, -0.1975],
         [-0.8523, -0.8307, -0.2932, -0.5887]]),
 tensor([[-0.2823, -0.3636, -0.3332, -0.2197],
         [-0.0754, -0.0746, -0.5465, -0.4379],
         [-0.6903, -0.7924, -0.5584, -0.1975],
         [-0.8523, -0.8307, -0.2932, -0.5887]]))

In [14]:
# Element wise multiplication
tensor * 3, torch.mul(tensor,3), tensor.mul(3)

(tensor([[2.1531, 1.9093, 2.0003, 2.3408],
         [2.7737, 2.7762, 1.3604, 1.6863],
         [0.9292, 0.6227, 1.3248, 2.4074],
         [0.4430, 0.5078, 2.1205, 1.2338]]),
 tensor([[2.1531, 1.9093, 2.0003, 2.3408],
         [2.7737, 2.7762, 1.3604, 1.6863],
         [0.9292, 0.6227, 1.3248, 2.4074],
         [0.4430, 0.5078, 2.1205, 1.2338]]),
 tensor([[2.1531, 1.9093, 2.0003, 2.3408],
         [2.7737, 2.7762, 1.3604, 1.6863],
         [0.9292, 0.6227, 1.3248, 2.4074],
         [0.4430, 0.5078, 2.1205, 1.2338]]))

In [15]:
# Division
tensor / 2, torch.divide(tensor, 2), tensor.divide(2)

(tensor([[0.3589, 0.3182, 0.3334, 0.3901],
         [0.4623, 0.4627, 0.2267, 0.2811],
         [0.1549, 0.1038, 0.2208, 0.4012],
         [0.0738, 0.0846, 0.3534, 0.2056]]),
 tensor([[0.3589, 0.3182, 0.3334, 0.3901],
         [0.4623, 0.4627, 0.2267, 0.2811],
         [0.1549, 0.1038, 0.2208, 0.4012],
         [0.0738, 0.0846, 0.3534, 0.2056]]),
 tensor([[0.3589, 0.3182, 0.3334, 0.3901],
         [0.4623, 0.4627, 0.2267, 0.2811],
         [0.1549, 0.1038, 0.2208, 0.4012],
         [0.0738, 0.0846, 0.3534, 0.2056]]))

### Matrix multiplication (Multiplying Tensors)
##### Dot product
Rules of matric multiplication
* The inner dimention of two tensors must be same
    - `(3,2) * (3,4)` won't work
    - `(3,2) * (2,4)` will work
* The dimention of the result will be same as the outer dimentions of the operant matrices
    - `(3,2) * (4,2)` will result the matrix with the shape of `(2,4)`
    - `(2) * (2)` will result the matrix with the shape of `(1)` ( matmul(scalar, scalar ) == scalar )

In [16]:
# note that the inner dimentions of Tensors "tensor" and "tensor2"
tensor2 = torch.rand([4,6])
tensor @ tensor2, torch.matmul(tensor,tensor2), tensor.matmul(tensor2)

(tensor([[2.0309, 1.2293, 1.4701, 1.8268, 1.8114, 0.7849],
         [2.2597, 1.2164, 1.2229, 2.0749, 1.6194, 0.7862],
         [1.1094, 0.7601, 1.1491, 0.9183, 1.2754, 0.5669],
         [0.9320, 0.6781, 0.9602, 0.8618, 1.1440, 0.3399]]),
 tensor([[2.0309, 1.2293, 1.4701, 1.8268, 1.8114, 0.7849],
         [2.2597, 1.2164, 1.2229, 2.0749, 1.6194, 0.7862],
         [1.1094, 0.7601, 1.1491, 0.9183, 1.2754, 0.5669],
         [0.9320, 0.6781, 0.9602, 0.8618, 1.1440, 0.3399]]),
 tensor([[2.0309, 1.2293, 1.4701, 1.8268, 1.8114, 0.7849],
         [2.2597, 1.2164, 1.2229, 2.0749, 1.6194, 0.7862],
         [1.1094, 0.7601, 1.1491, 0.9183, 1.2754, 0.5669],
         [0.9320, 0.6781, 0.9602, 0.8618, 1.1440, 0.3399]]))

#### Difference between Pytorch functions and hardcoded function

In [17]:
%time
torch.matmul(tensor,tensor2)

CPU times: user 5 μs, sys: 1 μs, total: 6 μs
Wall time: 10.7 μs


tensor([[2.0309, 1.2293, 1.4701, 1.8268, 1.8114, 0.7849],
        [2.2597, 1.2164, 1.2229, 2.0749, 1.6194, 0.7862],
        [1.1094, 0.7601, 1.1491, 0.9183, 1.2754, 0.5669],
        [0.9320, 0.6781, 0.9602, 0.8618, 1.1440, 0.3399]])

##### Transpose of a matirx
Transpose will interchange coloums and rows \
`tensor([2,3]).T ==> tensor([3,2])`
* the transpose can be used to fix the shape not mach problems in matrix multiplication

In [18]:
t1 = torch.tensor([[1,2,3,],
                   [4,5,6]])
t1,t1.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [19]:
# transpose of the matrix t1
t1.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

### Reshaping, Stacking, Squeezing, Unsqueezing
* Reshaping - Reshapes input tensor to a difined shape
* View - Returns a view of the tensor of cirtain shape but keep the memory as the original tensor
* Stacking - Combines multiple tensors on top of eachother (vstack) or side-by-side (hstack)
* Squeezing - Removes all `1` dimentions from the tensor
* Unsqueezing - Adds a `1` dimentions to the tensor
* Permute - Return a view of the input tensor with dimentions permuted

In [23]:
x = torch.arange(1,10)
x.shape

torch.Size([9])

In [29]:
x_reshaped = x.reshape([1,9])
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [30]:
x_reshaped = x.reshape([3,3])
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [33]:
x_view = x.view(3,3)
x_view

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [35]:
# changing x_view changes x, because the view share same memory
x_view[:,0] = 4
x_view, x

(tensor([[4, 2, 3],
         [4, 5, 6],
         [4, 8, 9]]),
 tensor([4, 2, 3, 4, 5, 6, 4, 8, 9]))

In [40]:
# Stack tensors

x_stacked = torch.stack([x,x,x,x])
x_stacked, torch.vstack([x,x,x,x])

(tensor([[4, 2, 3, 4, 5, 6, 4, 8, 9],
         [4, 2, 3, 4, 5, 6, 4, 8, 9],
         [4, 2, 3, 4, 5, 6, 4, 8, 9],
         [4, 2, 3, 4, 5, 6, 4, 8, 9]]),
 tensor([[4, 2, 3, 4, 5, 6, 4, 8, 9],
         [4, 2, 3, 4, 5, 6, 4, 8, 9],
         [4, 2, 3, 4, 5, 6, 4, 8, 9],
         [4, 2, 3, 4, 5, 6, 4, 8, 9]]))

In [41]:
x_stacked = torch.stack([x,x,x,x],dim = 1)
x_stacked, torch.hstack([x,x,x,x])

(tensor([[4, 4, 4, 4],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [4, 4, 4, 4],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]),
 tensor([4, 2, 3, 4, 5, 6, 4, 8, 9, 4, 2, 3, 4, 5, 6, 4, 8, 9, 4, 2, 3, 4, 5, 6,
         4, 8, 9, 4, 2, 3, 4, 5, 6, 4, 8, 9]))

In [50]:
# squeezing tensor
y = x.reshape([1,1,9,1])
y.shape,y

(torch.Size([1, 1, 9, 1]),
 tensor([[[[4],
           [2],
           [3],
           [4],
           [5],
           [6],
           [4],
           [8],
           [9]]]]))

In [52]:
y_squeezed = y.squeeze()
y.squeeze(), torch.squeeze(y)

(tensor([4, 2, 3, 4, 5, 6, 4, 8, 9]), tensor([4, 2, 3, 4, 5, 6, 4, 8, 9]))

In [53]:
# Unsqueezing tensor

y_squeezed.unsqueeze(dim=0)

tensor([[4, 2, 3, 4, 5, 6, 4, 8, 9]])

In [54]:
y_squeezed.unsqueeze(dim=1)

tensor([[4],
        [2],
        [3],
        [4],
        [5],
        [6],
        [4],
        [8],
        [9]])

In [59]:
# Permuting tensors (swapping dims of tensors)

perm = torch.randn(2,5,3)
perm, perm.shape

(tensor([[[-0.4370, -0.0075,  0.0718],
          [ 1.0566,  0.6150, -0.4108],
          [-0.6563,  1.7070,  0.4566],
          [-0.9054, -0.7563,  0.7667],
          [ 0.3333,  0.2853,  0.1475]],
 
         [[-0.1629, -0.2944,  0.7967],
          [ 0.3163,  0.9613,  1.5175],
          [ 1.5208, -0.4397,  0.0984],
          [ 0.7893, -0.4037,  1.3342],
          [-0.3732,  1.5044, -1.4545]]]),
 torch.Size([2, 5, 3]))

In [65]:
torch.permute(perm, [1,0,2]), torch.permute(perm,[1,0,2]).shape

(tensor([[[-0.4370, -0.0075,  0.0718],
          [-0.1629, -0.2944,  0.7967]],
 
         [[ 1.0566,  0.6150, -0.4108],
          [ 0.3163,  0.9613,  1.5175]],
 
         [[-0.6563,  1.7070,  0.4566],
          [ 1.5208, -0.4397,  0.0984]],
 
         [[-0.9054, -0.7563,  0.7667],
          [ 0.7893, -0.4037,  1.3342]],
 
         [[ 0.3333,  0.2853,  0.1475],
          [-0.3732,  1.5044, -1.4545]]]),
 torch.Size([5, 2, 3]))

### Pytorch and Numpy
* pytorch tensor -> numpy array `torch.Tensor.numpy()`
* numpy array -> pytorch tensor `torch.from_numpy(ndarray)`

In [66]:
import numpy as np

In [70]:
# np array to tensor
np_arr = np.arange(1,10)
np_to_tensor = torch.from_numpy(np_arr)
np_to_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# tensor to np