In [2]:
import torch

### First Tensor
Creating tensors with different dimentions using pytorch

In [3]:
tensor = torch.tensor(5) # scalar

# 1 dimentional tensor
tensor1 = torch.tensor([3,2,5,6,3,6,3])  # vector 
print(tensor1.shape)

# 2 dimentional tensor
# matrix
tensor2 = torch.tensor([[1,2,3,4,5],
                        [6,7,8,9,0]])

# [4,5] tensor with random elements; rand(dim) method creates ramdom tensor with given dimention 
random_tensor = torch.rand([4,5])
random_tensor

torch.Size([7])


tensor([[0.4400, 0.8386, 0.1807, 0.0321, 0.5671],
        [0.8514, 0.9981, 0.2854, 0.5818, 0.4434],
        [0.2421, 0.2100, 0.8544, 0.1743, 0.5291],
        [0.1240, 0.5313, 0.7624, 0.0385, 0.7460]])

In [4]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [5]:
# shape of the tensor
tensor1.shape
# OR
tensor1.size()

torch.Size([7])

### Tensor Datatypes

Tensors can have many datatype such as float16, float32, int32, int16 etc.
tensor.dtype contain data type of the tensor

In [6]:
# tensor.dtype contain data type of the tensor
random_tensor.dtype

torch.float32

In [7]:
# changing type of a tensor: type()
f16tensor = random_tensor.type(torch.float16)
f16tensor.dtype

torch.float16

### Tensor aggregation
finding min, max, sum, mean etc of a tensor

In [8]:
x = torch.tensor([1,2,3,4,5,6,7,8])

# finding min and max of the tensor x
torch.min(x), torch.max(x)
# OR
x.min(),x.max()

(tensor(1), tensor(8))

In [9]:
#finding sum of the tensor
torch.sum(x), x.sum()

(tensor(36), tensor(36))

In [10]:
# finding the mean of the tensor x
# to find the mean, the tensor have to be floating point or complex dtype
# x.mean() or torch.mean(x) don't work, because dtype of tensor x in int64 (long)
x = x.type(torch.float32)
x.mean(), torch.mean(x)

(tensor(4.5000), tensor(4.5000))

In [11]:
# finding positional min and max (position of the min and max elment in the tensor)

x.argmin(), x.argmax()

(tensor(0), tensor(7))

### Manipulating tensors (Tensor operations)

Tensor operations:
* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matix Multiplication

In [12]:
tensor = torch.rand([4,4])
tensor

tensor([[0.7900, 0.2408, 0.3314, 0.7792],
        [0.2433, 0.7439, 0.3045, 0.8155],
        [0.6464, 0.1051, 0.9808, 0.6916],
        [0.8134, 0.0554, 0.7316, 0.9367]])

In [13]:
# Addition
tensor + 1, torch.add(tensor,1), tensor.add(1)

(tensor([[1.7900, 1.2408, 1.3314, 1.7792],
         [1.2433, 1.7439, 1.3045, 1.8155],
         [1.6464, 1.1051, 1.9808, 1.6916],
         [1.8134, 1.0554, 1.7316, 1.9367]]),
 tensor([[1.7900, 1.2408, 1.3314, 1.7792],
         [1.2433, 1.7439, 1.3045, 1.8155],
         [1.6464, 1.1051, 1.9808, 1.6916],
         [1.8134, 1.0554, 1.7316, 1.9367]]),
 tensor([[1.7900, 1.2408, 1.3314, 1.7792],
         [1.2433, 1.7439, 1.3045, 1.8155],
         [1.6464, 1.1051, 1.9808, 1.6916],
         [1.8134, 1.0554, 1.7316, 1.9367]]))

In [14]:
#subtaction
tensor - 1, torch.subtract(tensor,1), tensor.subtract(1)

(tensor([[-0.2100, -0.7592, -0.6686, -0.2208],
         [-0.7567, -0.2561, -0.6955, -0.1845],
         [-0.3536, -0.8949, -0.0192, -0.3084],
         [-0.1866, -0.9446, -0.2684, -0.0633]]),
 tensor([[-0.2100, -0.7592, -0.6686, -0.2208],
         [-0.7567, -0.2561, -0.6955, -0.1845],
         [-0.3536, -0.8949, -0.0192, -0.3084],
         [-0.1866, -0.9446, -0.2684, -0.0633]]),
 tensor([[-0.2100, -0.7592, -0.6686, -0.2208],
         [-0.7567, -0.2561, -0.6955, -0.1845],
         [-0.3536, -0.8949, -0.0192, -0.3084],
         [-0.1866, -0.9446, -0.2684, -0.0633]]))

In [15]:
# Element wise multiplication
tensor * 3, torch.mul(tensor,3), tensor.mul(3)

(tensor([[2.3700, 0.7223, 0.9942, 2.3377],
         [0.7299, 2.2317, 0.9136, 2.4464],
         [1.9391, 0.3154, 2.9425, 2.0748],
         [2.4401, 0.1661, 2.1947, 2.8102]]),
 tensor([[2.3700, 0.7223, 0.9942, 2.3377],
         [0.7299, 2.2317, 0.9136, 2.4464],
         [1.9391, 0.3154, 2.9425, 2.0748],
         [2.4401, 0.1661, 2.1947, 2.8102]]),
 tensor([[2.3700, 0.7223, 0.9942, 2.3377],
         [0.7299, 2.2317, 0.9136, 2.4464],
         [1.9391, 0.3154, 2.9425, 2.0748],
         [2.4401, 0.1661, 2.1947, 2.8102]]))

In [16]:
# Division
tensor / 2, torch.divide(tensor, 2), tensor.divide(2)

(tensor([[0.3950, 0.1204, 0.1657, 0.3896],
         [0.1216, 0.3720, 0.1523, 0.4077],
         [0.3232, 0.0526, 0.4904, 0.3458],
         [0.4067, 0.0277, 0.3658, 0.4684]]),
 tensor([[0.3950, 0.1204, 0.1657, 0.3896],
         [0.1216, 0.3720, 0.1523, 0.4077],
         [0.3232, 0.0526, 0.4904, 0.3458],
         [0.4067, 0.0277, 0.3658, 0.4684]]),
 tensor([[0.3950, 0.1204, 0.1657, 0.3896],
         [0.1216, 0.3720, 0.1523, 0.4077],
         [0.3232, 0.0526, 0.4904, 0.3458],
         [0.4067, 0.0277, 0.3658, 0.4684]]))

### Matrix multiplication (Multiplying Tensors)
##### Dot product
Rules of matric multiplication
* The inner dimention of two tensors must be same
    - `(3,2) * (3,4)` won't work
    - `(3,2) * (2,4)` will work
* The dimention of the result will be same as the outer dimentions of the operant matrices
    - `(3,2) * (4,2)` will result the matrix with the shape of `(2,4)`
    - `(2) * (2)` will result the matrix with the shape of `(1)` ( matmul(scalar, scalar ) == scalar )

In [17]:
# note that the inner dimentions of Tensors "tensor" and "tensor2"
tensor2 = torch.rand([4,6])
tensor @ tensor2, torch.matmul(tensor,tensor2), tensor.matmul(tensor2)

(tensor([[1.1925, 0.4575, 0.8683, 0.3645, 0.7613, 0.8851],
         [0.9553, 0.5252, 0.5632, 0.3227, 0.8478, 0.5372],
         [1.1245, 0.6102, 0.9532, 0.6886, 1.2106, 0.8714],
         [1.2928, 0.5507, 1.0687, 0.5979, 1.1051, 1.0017]]),
 tensor([[1.1925, 0.4575, 0.8683, 0.3645, 0.7613, 0.8851],
         [0.9553, 0.5252, 0.5632, 0.3227, 0.8478, 0.5372],
         [1.1245, 0.6102, 0.9532, 0.6886, 1.2106, 0.8714],
         [1.2928, 0.5507, 1.0687, 0.5979, 1.1051, 1.0017]]),
 tensor([[1.1925, 0.4575, 0.8683, 0.3645, 0.7613, 0.8851],
         [0.9553, 0.5252, 0.5632, 0.3227, 0.8478, 0.5372],
         [1.1245, 0.6102, 0.9532, 0.6886, 1.2106, 0.8714],
         [1.2928, 0.5507, 1.0687, 0.5979, 1.1051, 1.0017]]))

#### Difference between Pytorch functions and hardcoded function

In [18]:
%time
torch.matmul(tensor,tensor2)

CPU times: user 3 μs, sys: 0 ns, total: 3 μs
Wall time: 6.68 μs


tensor([[1.1925, 0.4575, 0.8683, 0.3645, 0.7613, 0.8851],
        [0.9553, 0.5252, 0.5632, 0.3227, 0.8478, 0.5372],
        [1.1245, 0.6102, 0.9532, 0.6886, 1.2106, 0.8714],
        [1.2928, 0.5507, 1.0687, 0.5979, 1.1051, 1.0017]])

##### Transpose of a matirx
Transpose will interchange coloums and rows \
`tensor([2,3]).T ==> tensor([3,2])`
* the transpose can be used to fix the shape not mach problems in matrix multiplication

In [19]:
t1 = torch.tensor([[1,2,3,],
                   [4,5,6]])
t1,t1.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [20]:
# transpose of the matrix t1
t1.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

### Reshaping, Stacking, Squeezing, Unsqueezing
* Reshaping - Reshapes input tensor to a difined shape
* View - Returns a view of the tensor of cirtain shape but keep the memory as the original tensor
* Stacking - Combines multiple tensors on top of eachother (vstack) or side-by-side (hstack)
* Squeezing - Removes all `1` dimentions from the tensor
* Unsqueezing - Adds a `1` dimentions to the tensor
* Permute - Return a view of the input tensor with dimentions permuted

In [21]:
x = torch.arange(1,10)
x.shape

torch.Size([9])

In [22]:
x_reshaped = x.reshape([1,9])
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
x_reshaped = x.reshape([3,3])
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
x_view = x.view(3,3)
x_view

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
# changing x_view changes x, because the view share same memory
x_view[:,0] = 4
x_view, x

(tensor([[4, 2, 3],
         [4, 5, 6],
         [4, 8, 9]]),
 tensor([4, 2, 3, 4, 5, 6, 4, 8, 9]))

In [26]:
# Stack tensors

x_stacked = torch.stack([x,x,x,x])
x_stacked, torch.vstack([x,x,x,x])

(tensor([[4, 2, 3, 4, 5, 6, 4, 8, 9],
         [4, 2, 3, 4, 5, 6, 4, 8, 9],
         [4, 2, 3, 4, 5, 6, 4, 8, 9],
         [4, 2, 3, 4, 5, 6, 4, 8, 9]]),
 tensor([[4, 2, 3, 4, 5, 6, 4, 8, 9],
         [4, 2, 3, 4, 5, 6, 4, 8, 9],
         [4, 2, 3, 4, 5, 6, 4, 8, 9],
         [4, 2, 3, 4, 5, 6, 4, 8, 9]]))

In [27]:
x_stacked = torch.stack([x,x,x,x],dim = 1)
x_stacked, torch.hstack([x,x,x,x])

(tensor([[4, 4, 4, 4],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [4, 4, 4, 4],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]),
 tensor([4, 2, 3, 4, 5, 6, 4, 8, 9, 4, 2, 3, 4, 5, 6, 4, 8, 9, 4, 2, 3, 4, 5, 6,
         4, 8, 9, 4, 2, 3, 4, 5, 6, 4, 8, 9]))

In [28]:
# squeezing tensor
y = x.reshape([1,1,9,1])
y.shape,y

(torch.Size([1, 1, 9, 1]),
 tensor([[[[4],
           [2],
           [3],
           [4],
           [5],
           [6],
           [4],
           [8],
           [9]]]]))

In [29]:
y_squeezed = y.squeeze()
y.squeeze(), torch.squeeze(y)

(tensor([4, 2, 3, 4, 5, 6, 4, 8, 9]), tensor([4, 2, 3, 4, 5, 6, 4, 8, 9]))

In [30]:
# Unsqueezing tensor

y_squeezed.unsqueeze(dim=0)

tensor([[4, 2, 3, 4, 5, 6, 4, 8, 9]])

In [31]:
y_squeezed.unsqueeze(dim=1)

tensor([[4],
        [2],
        [3],
        [4],
        [5],
        [6],
        [4],
        [8],
        [9]])

In [32]:
# Permuting tensors (swapping dims of tensors)

perm = torch.randn(2,5,3)
perm, perm.shape

(tensor([[[ 1.1173, -0.2673,  0.3051],
          [-1.2595,  0.0255,  0.2560],
          [ 0.6929,  0.4573, -2.1713],
          [-2.0475, -1.4266,  0.4749],
          [ 0.0084,  1.3386, -0.6466]],
 
         [[ 0.1160,  0.2101, -1.3020],
          [ 0.7636, -0.4723, -1.2646],
          [-0.7891,  0.7751,  0.3921],
          [ 0.9658,  0.9532,  1.4701],
          [ 0.0108, -0.6364, -1.4211]]]),
 torch.Size([2, 5, 3]))

In [33]:
torch.permute(perm, [1,0,2]), torch.permute(perm,[1,0,2]).shape

(tensor([[[ 1.1173, -0.2673,  0.3051],
          [ 0.1160,  0.2101, -1.3020]],
 
         [[-1.2595,  0.0255,  0.2560],
          [ 0.7636, -0.4723, -1.2646]],
 
         [[ 0.6929,  0.4573, -2.1713],
          [-0.7891,  0.7751,  0.3921]],
 
         [[-2.0475, -1.4266,  0.4749],
          [ 0.9658,  0.9532,  1.4701]],
 
         [[ 0.0084,  1.3386, -0.6466],
          [ 0.0108, -0.6364, -1.4211]]]),
 torch.Size([5, 2, 3]))

### Pytorch and Numpy
* pytorch tensor -> numpy array `torch.Tensor.numpy()`
* numpy array -> pytorch tensor `torch.from_numpy(ndarray)`

In [34]:
import numpy as np

In [35]:
# np array to tensor
np_arr = np.arange(1,10)
np_to_tensor = torch.from_numpy(np_arr)
np_to_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# tensor to np array\
p_tensor = torch.arange(1,10)
tensor_to_arr = torch.Tensor.numpy(p_tensor)
tensor_to_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Reproduciblity of randomness
To reduce randomness, we use random seed.

random seed flavours randomness

In [37]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Tensors on GPU

In [39]:
torch.cuda.is_available()

False

In [40]:
torch.cuda.device_count()

0

In [41]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [42]:
tensor = torch.tensor([1,2,3,4])
tensor.device

device(type='cpu')

In [43]:
tensor_GPU = tensor.to(device)
tensor_GPU.device

device(type='cpu')

In [44]:
tensor_CPU = tensor_GPU.cpu()
tensor_CPU.device

device(type='cpu')