In [1]:
import torch

### First Tensor
Creating tensors with different dimentions using pytorch

In [2]:
tensor = torch.tensor(5) # scalar

# 1 dimentional tensor
tensor1 = torch.tensor([3,2,5,6,3,6,3])  # vector 
print(tensor1.shape)

# 2 dimentional tensor
# matrix
tensor2 = torch.tensor([[1,2,3,4,5],
                        [6,7,8,9,0]])

# [4,5] tensor with random elements; rand(dim) method creates ramdom tensor with given dimention 
random_tensor = torch.rand([4,5])
random_tensor

torch.Size([7])


tensor([[0.1102, 0.2778, 0.8505, 0.3274, 0.1234],
        [0.2596, 0.6155, 0.4405, 0.0880, 0.8024],
        [0.2953, 0.2930, 0.0324, 0.8754, 0.7763],
        [0.9273, 0.2501, 0.5818, 0.2358, 0.7715]])

In [3]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [4]:
# shape of the tensor
tensor1.shape
# OR
tensor1.size()

torch.Size([7])

### Tensor Datatypes

Tensors can have many datatype such as float16, float32, int32, int16 etc.
tensor.dtype contain data type of the tensor

In [5]:
# tensor.dtype contain data type of the tensor
random_tensor.dtype

torch.float32

In [6]:
# changing type of a tensor: type()
f16tensor = random_tensor.type(torch.float16)
f16tensor.dtype

torch.float16

### Tensor aggregation
finding min, max, sum, mean etc of a tensor

In [7]:
x = torch.tensor([1,2,3,4,5,6,7,8])

# finding min and max of the tensor x
torch.min(x), torch.max(x)
# OR
x.min(),x.max()

(tensor(1), tensor(8))

In [8]:
#finding sum of the tensor
torch.sum(x), x.sum()

(tensor(36), tensor(36))

In [9]:
# finding the mean of the tensor x
# to find the mean, the tensor have to be floating point or complex dtype
# x.mean() or torch.mean(x) don't work, because dtype of tensor x in int64 (long)
x = x.type(torch.float32)
x.mean(), torch.mean(x)

(tensor(4.5000), tensor(4.5000))

In [10]:
# finding positional min and max (position of the min and max elment in the tensor)

x.argmin(), x.argmax()

(tensor(0), tensor(7))

### Manipulating tensors (Tensor operations)

Tensor operations:
* Addition
* Subtraction
* Multiplication (element wise)
* Division
* Matix Multiplication

In [11]:
tensor = torch.rand([4,4])
tensor

tensor([[0.1970, 0.5195, 0.1607, 0.9909],
        [0.2983, 0.3013, 0.7022, 0.8666],
        [0.1532, 0.8221, 0.1558, 0.1137],
        [0.6807, 0.5345, 0.6778, 0.6449]])

In [12]:
# Addition
tensor + 1, torch.add(tensor,1), tensor.add(1)

(tensor([[1.1970, 1.5195, 1.1607, 1.9909],
         [1.2983, 1.3013, 1.7022, 1.8666],
         [1.1532, 1.8221, 1.1558, 1.1137],
         [1.6807, 1.5345, 1.6778, 1.6449]]),
 tensor([[1.1970, 1.5195, 1.1607, 1.9909],
         [1.2983, 1.3013, 1.7022, 1.8666],
         [1.1532, 1.8221, 1.1558, 1.1137],
         [1.6807, 1.5345, 1.6778, 1.6449]]),
 tensor([[1.1970, 1.5195, 1.1607, 1.9909],
         [1.2983, 1.3013, 1.7022, 1.8666],
         [1.1532, 1.8221, 1.1558, 1.1137],
         [1.6807, 1.5345, 1.6778, 1.6449]]))

In [13]:
#subtaction
tensor - 1, torch.subtract(tensor,1), tensor.subtract(1)

(tensor([[-0.8030, -0.4805, -0.8393, -0.0091],
         [-0.7017, -0.6987, -0.2978, -0.1334],
         [-0.8468, -0.1779, -0.8442, -0.8863],
         [-0.3193, -0.4655, -0.3222, -0.3551]]),
 tensor([[-0.8030, -0.4805, -0.8393, -0.0091],
         [-0.7017, -0.6987, -0.2978, -0.1334],
         [-0.8468, -0.1779, -0.8442, -0.8863],
         [-0.3193, -0.4655, -0.3222, -0.3551]]),
 tensor([[-0.8030, -0.4805, -0.8393, -0.0091],
         [-0.7017, -0.6987, -0.2978, -0.1334],
         [-0.8468, -0.1779, -0.8442, -0.8863],
         [-0.3193, -0.4655, -0.3222, -0.3551]]))

In [14]:
# Element wise multiplication
tensor * 3, torch.mul(tensor,3), tensor.mul(3)

(tensor([[0.5911, 1.5586, 0.4820, 2.9727],
         [0.8949, 0.9038, 2.1066, 2.5998],
         [0.4596, 2.4662, 0.4673, 0.3410],
         [2.0422, 1.6035, 2.0335, 1.9348]]),
 tensor([[0.5911, 1.5586, 0.4820, 2.9727],
         [0.8949, 0.9038, 2.1066, 2.5998],
         [0.4596, 2.4662, 0.4673, 0.3410],
         [2.0422, 1.6035, 2.0335, 1.9348]]),
 tensor([[0.5911, 1.5586, 0.4820, 2.9727],
         [0.8949, 0.9038, 2.1066, 2.5998],
         [0.4596, 2.4662, 0.4673, 0.3410],
         [2.0422, 1.6035, 2.0335, 1.9348]]))

In [15]:
# Division
tensor / 2, torch.divide(tensor, 2), tensor.divide(2)

(tensor([[0.0985, 0.2598, 0.0803, 0.4955],
         [0.1491, 0.1506, 0.3511, 0.4333],
         [0.0766, 0.4110, 0.0779, 0.0568],
         [0.3404, 0.2672, 0.3389, 0.3225]]),
 tensor([[0.0985, 0.2598, 0.0803, 0.4955],
         [0.1491, 0.1506, 0.3511, 0.4333],
         [0.0766, 0.4110, 0.0779, 0.0568],
         [0.3404, 0.2672, 0.3389, 0.3225]]),
 tensor([[0.0985, 0.2598, 0.0803, 0.4955],
         [0.1491, 0.1506, 0.3511, 0.4333],
         [0.0766, 0.4110, 0.0779, 0.0568],
         [0.3404, 0.2672, 0.3389, 0.3225]]))

### Matrix multiplication (Multiplying Tensors)
##### Dot product
Rules of matric multiplication
* The inner dimention of two tensors must be same
    - `(3,2) * (3,4)` won't work
    - `(3,2) * (2,4)` will work
* The dimention of the result will be same as the outer dimentions of the operant matrices
    - `(3,2) * (4,2)` will result the matrix with the shape of `(2,4)`
    - `(2) * (2)` will result the matrix with the shape of `(1)` ( matmul(scalar, scalar ) == scalar )

In [16]:
# note that the inner dimentions of Tensors "tensor" and "tensor2"
tensor2 = torch.rand([4,6])
tensor @ tensor2, torch.matmul(tensor,tensor2), tensor.matmul(tensor2)

(tensor([[0.6320, 0.9773, 0.8344, 0.5355, 0.8302, 1.4864],
         [0.8670, 1.1040, 0.8497, 0.7526, 0.9519, 1.8809],
         [0.3122, 0.5286, 0.7825, 0.5761, 0.3736, 0.8121],
         [1.0359, 1.2054, 1.0697, 1.0435, 1.0150, 2.1295]]),
 tensor([[0.6320, 0.9773, 0.8344, 0.5355, 0.8302, 1.4864],
         [0.8670, 1.1040, 0.8497, 0.7526, 0.9519, 1.8809],
         [0.3122, 0.5286, 0.7825, 0.5761, 0.3736, 0.8121],
         [1.0359, 1.2054, 1.0697, 1.0435, 1.0150, 2.1295]]),
 tensor([[0.6320, 0.9773, 0.8344, 0.5355, 0.8302, 1.4864],
         [0.8670, 1.1040, 0.8497, 0.7526, 0.9519, 1.8809],
         [0.3122, 0.5286, 0.7825, 0.5761, 0.3736, 0.8121],
         [1.0359, 1.2054, 1.0697, 1.0435, 1.0150, 2.1295]]))

#### Difference between Pytorch functions and hardcoded function

In [17]:
%time
torch.matmul(tensor,tensor2)

CPU times: user 3 μs, sys: 1 μs, total: 4 μs
Wall time: 7.39 μs


tensor([[0.6320, 0.9773, 0.8344, 0.5355, 0.8302, 1.4864],
        [0.8670, 1.1040, 0.8497, 0.7526, 0.9519, 1.8809],
        [0.3122, 0.5286, 0.7825, 0.5761, 0.3736, 0.8121],
        [1.0359, 1.2054, 1.0697, 1.0435, 1.0150, 2.1295]])

##### Transpose of a matirx
Transpose will interchange coloums and rows \
`tensor([2,3]).T ==> tensor([3,2])`
* the transpose can be used to fix the shape note

In [20]:
t1 = torch.tensor([[1,2,3,],
                   [4,5,6]])
t1,t1.shape

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 torch.Size([2, 3]))

In [23]:
# transpose of the matrix t1
t1.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])