In [2]:
import torch
import torch.nn as nn

In [3]:
weights = 0.7
bias = 0.3

X = torch.arange(0,20,0.2)
X.shape

torch.Size([100])

In [4]:
y = X * weights + bias
y.shape

torch.Size([100])

In [259]:
train_split = int(0.7 * len(X))
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]
X_train.shape, X_test.shape, y_train.shape, y_test.shape

(torch.Size([70]), torch.Size([30]), torch.Size([70]), torch.Size([30]))

In [260]:
class LinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float))
        self.bias = nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float))
    def forward(self,x:torch.Tensor)-> torch.Tensor:
        return self.weights * x + self.bias

In [261]:
torch.manual_seed(42)
model = LinearRegression()

In [262]:
model.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [263]:
list(model.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]

In [264]:
loss_fn = nn.L1Loss()
optimizer = torch.optim.SGD(params=model.parameters(),lr=0.00001)

In [265]:
model.state_dict()

OrderedDict([('weights', tensor([0.3367])), ('bias', tensor([0.1288]))])

In [308]:
epochs = 10000
for i in range(epochs):
    model.train()
    y_pred = model(X_train)
    loss = loss_fn(y_pred,y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    model.eval()
print(f"loss:{loss}")
model.state_dict()

loss:0.0004451313288882375


OrderedDict([('weights', tensor([0.7000])), ('bias', tensor([0.3000]))])

In [258]:
with torch.inference_mode():
    y_pred_test = model(X_test)
    j_test = loss_fn(y_test,y_pred_test)
    print(f"test loss:{j_test}")
X_test[0]*0.7006+0.3000

test loss:3.3317246437072754


tensor(7.3761)

In [256]:
X_test,y_test

(tensor([10.1000, 10.2400, 10.3800, 10.5200, 10.6600, 10.8000, 10.9400, 11.0800,
         11.2200, 11.3600, 11.5000, 11.6400, 11.7800, 11.9200, 12.0600, 12.2000,
         12.3400, 12.4800, 12.6200, 12.7600, 12.9000, 13.0400, 13.1800, 13.3200,
         13.4600, 13.6000, 13.7400, 13.8800, 14.0200, 14.1600]),
 tensor([10.1000, 10.2400, 10.3800, 10.5200, 10.6600, 10.8000, 10.9400, 11.0800,
         11.2200, 11.3600, 11.5000, 11.6400, 11.7800, 11.9200, 12.0600, 12.2000,
         12.3400, 12.4800, 12.6200, 12.7600, 12.9000, 13.0400, 13.1800, 13.3200,
         13.4600, 13.6000, 13.7400, 13.8800, 14.0200, 14.1600]))